---
- name: Converge
  hosts: all
  become: true
  gather_facts: yes
  #vars_files:
  #  - ../../defaults/main.yml
  #vars:


  tasks:
    - name: "Include ansible_molecule_template"
      include_role:
        name: "ansible_molecule_template"

  #roles:
    #- role: habbis.ansible_molecule_template
